version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: on-failure
    container_name: mongodb
    env_file:
      - .env
    ports:
      - 27017:27017

  redisdb:
    image: redis:latest
    restart: on-failure
    ports:
      - 6379:6379

  api:
    container_name: go_chat_server
    restart: on-failure
    build: .
    command: bash -c "rm -rf ./tmp && air"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8080:8080
    links:
      - redisdb
